name: Production

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: Deploy
    strategy:
      matrix:
        app: [ash_table_poc]
        prod_env: [prod]
        os: [ubuntu-latest]
        port: [8070]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into GHCR
        run: echo "${{secrets.GITHUB_TOKEN}}" | docker login https://ghcr.io -u ${{github.actor}} --password-stdin

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/mxgrn/${{matrix.app}}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Pull image on host, restart, run migrations
        uses: appleboy/ssh-action@master
        with:
          host: "5.75.226.35"
          sync: true
          username: deploy
          key: ${{ secrets.DEPLOYMENT_KEY }}
          script_stop: true
          script: |
            echo "${{secrets.GITHUB_TOKEN}}" | docker login https://ghcr.io -u ${{github.actor}} --password-stdin
            docker pull ghcr.io/mxgrn/${{matrix.app}}
            docker stop ${{matrix.app}}_${{matrix.prod_env}} || true
            docker rm ${{matrix.app}}_${{matrix.prod_env}} || true
            docker run --name=${{matrix.app}}_${{matrix.prod_env}} -d \
              --restart always \
              --network host \
              -e PORT=${{matrix.port}} \
              -e DATABASE_URL=${{secrets.DATABASE_URL}} \
              -e POOL_SIZE=2 \
              -e SECRET_KEY_BASE=${{secrets.SECRET_KEY_BASE}} \
              -e GITHUB_SHA=${{github.sha}} \
              -e PHX_HOST="ash-table-poc.mxgrn.com" \
              ghcr.io/mxgrn/${{matrix.app}}
            while [ "`docker inspect -f {{.State.Running}} ${{matrix.app}}_${{matrix.prod_env}}`" != "true" ]; do sleep 1; done
            sleep 20
            docker exec ${{matrix.app}}_${{matrix.prod_env}} /app/bin/migrate
            echo "Done."
